version: "3"
services:
  app:
    build: .
    volumes:
      - .:/django
    ports:
      - 7001:7001
    image: app:django
    container_name: django_container2
    command: python manage.py runserver 0.0.0.0:7001