FROM python:3.8-slim-buster
ENV PYTHONUNBUFFERED=1
# THIS IS GOING TO INSURE THAT ANY PYTHON OUTPUT IS SEND STRAIGHT TO TERMINOL.
# FOR EG - SO ANY ERROR LOGS IS GONA BE SEND STRAIGHT TO THE TERMINOL, WHICH IS IN THIS CASE OUR CONTAINER'S LOGS.
WORKDIR /django
COPY requirements.txt requirements.txt
RUN pip3 install -r requirements.txt

