version: "3"
services:
  app:
    build: .
    volumes:
      - .:/django
    ports:
      - 7000:7000
    image: app:django
    container_name: django_container
    command: python manage.py runserver 0.0.0.0:7000